import type { Metadata } from "next";
import "./globals.css";
import { Vesper_Libre } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import ScrollToTop from "@/components/footer/scrollToTop/ScrollToTop";
import ParallaxBackground from "@/components/division/parallaxBackground/ParallaxBackground";

const vesperLibre = Vesper_Libre({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: ["favicon.ico", "favicon-dark"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={vesperLibre.className}>
        <div className="container">
          <Navbar />
          <main id="main">{children}</main>
          <Footer />
          <ScrollToTop />
        </div>
      </body>
    </html>
  );
}
